# This is a basic workflow to help you get started with Actions

name: My first github Actions

# Controls when the workflow will run
on: [push]
 
jobs:
  build:  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9,3.10,3.11]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: action/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      

      # Runs a single command using the runners shell
      - name: install dependencies
        run: |
          python -m pip install -- upgrade pip
          pip install pytest
        

      # Runs a set of commands using the runners shell
      - name: Run test
        run: |
         cd src
         python -m pytest addtion.py
